load("//bazel/tools/clang_format:clang_format.bzl", "clang_format")

cc_library(
    name = "log",
    hdrs = ["log.h"],
    srcs = ["log.cpp"],
    visibility = ["//visibility:public"],
)

clang_format(name = "log")
